"use strict";
const elfCount = 27;
const elfSourceWidth = 11;
const elfSourceHeight = 24;
const highestElfIndex = elfCount-1;
const backgroundStreamMode = false;
const internalWidth = 750;
const internalHeight = 650;
const soundGain = 3 / 4;
const musicNodeGain = 0.2;
